controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
use app\models\Productos;
use app\models\Categorias;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionOfertas() {
        $query = Productos::find()->select("id, nombre, foto, descripcion")->where(["=", "oferta", "1"]);
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 2,
            ],
        ]);

        return $this->render('productos',[
            'dataProvider' => $dataProvider,
        ]);
    }
    
    public function actionInformacion() {
        $model = new \app\models\ContactForm();
        if ($model->load(Yii::$app->request->post())
                &&
            $model->contact(Yii::$app->params["informacion"])) {
            
            Yii::$app->session->setFlash('enviadaInformacion');
            
            return $this->refresh();
        }
        
        return $this->render("informacion",[
            "model" => $model,
        ]);
    }
    
    /**
     * 
     * Prueba de envio de correo electronico. No está en el menú.
     * 
     */
    public function actionCorreo() {
        $correo = new \app\models\ContactForm();
        $correo->asunto = "Probando este rollo";
        $correo->contenido = "El contenido del correo";
        $correo->correo = "cliente@correo.es";
        $correo->nombre = "Cliente";
        $correo->contact(Yii::$app->params["informacion"]);
    }
    
    public function actionContacto() {
        $model = new \app\models\FormularioContacto();
        if ($model->load(Yii::$app->request->post()) 
                &&
            $model->contact(Yii::$app->params["contacto"])) {
            Yii::$app->session->setFlash('enviadoContacto');
            
            return $this->refresh();
        }
        
        return $this->render("contacto", [
            "model" => $model,
        ]);
    }
    
    public function actionProductos() {
        $query = Productos::find()->select("id, nombre, foto, descripcion");
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 2,
            ],
        ]);

        return $this->render('productos',[
            'dataProvider' => $dataProvider,
        ]);
    }
    
    public function actionCategorias() {
        $query = Categorias::find()->select("id, nombre, foto, descripcion");
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 2,
            ],
        ]);

        return $this->render('categorias',[
            'dataProvider' => $dataProvider,
        ]);
    }
    
    public function actionDetallecategoria($id) {
        $model = new Categorias();
        $model = Categorias::find()->select('categorias.*')->where(['id' => $id])->one();

        $query = Productos::find()
                 ->joinWith("relacions",false,"INNER JOIN")
                 ->where("categoria=$id");

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);
        
        return $this->render("detalle_categoria",[
            'model' => $model,
            'dataProvider' => $dataProvider,
        ]);

    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'encodeLabels' => false,
        'items' => [
            ['label' => '<span class="glyphicon glyphicon-home"></span>&nbsp;Inicio', 'url' => ['/site/index']],
            ['label' => '<span class="glyphicon glyphicon-ok"></span>&nbsp;Ofertas', 'url' => ['/site/ofertas']],
            ['label' => '<span class="glyphicon glyphicon-th"></span>&nbsp;Productos', 'url' => ['/site/productos']],
            ['label' => '<span class="glyphicon glyphicon-list"></span>&nbsp;Categorías', 'url' => ['/site/categorias']],
            ['label' => '<span class="glyphicon glyphicon-info-sign"></span>&nbsp;Nosotros', 'items' => [
                    ['label' => 'Donde Estamos', 'url' => ['/site/dondeestamos']],
                    ['label' => 'Quienes Somos', 'url' => ['/site/quienessomos']],
                    ['label' => 'Nuestros productos', 'url' => ['/site/nuestrosproductos']],
                    '<li class="divider"></li>',
                    ['label' => 'Informacion', 'url' => ['/site/informacion']],
            ]],
            ['label' => '<span class="glyphicon glyphicon-user"></span>&nbsp;Contacto', 'url' => ['/site/contacto']],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Oscar Megía López 2020</p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>