controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
use app\models\Productos;
use app\models\Categorias;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionOfertas() {
        $query = Productos::find()->select("id, nombre, foto, descripcion")->where(["=", "oferta", "1"]);
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 2,
            ],
        ]);

        return $this->render('productos',[
            'dataProvider' => $dataProvider,
        ]);
    }
    
    public function actionInformacion() {
        $model = new \app\models\ContactForm();
        if ($model->load(Yii::$app->request->post())
                &&
            $model->contact(Yii::$app->params["informacion"])) {
            
            Yii::$app->session->setFlash('enviadaInformacion');
            
            return $this->refresh();
        }
        
        return $this->render("informacion",[
            "model" => $model,
        ]);
    }
    
    /**
     * 
     * Prueba de envio de correo electronico. No está en el menú.
     * 
     */
    public function actionCorreo() {
        $correo = new \app\models\ContactForm();
        $correo->asunto = "Probando este rollo";
        $correo->contenido = "El contenido del correo";
        $correo->correo = "cliente@correo.es";
        $correo->nombre = "Cliente";
        $correo->contact(Yii::$app->params["informacion"]);
    }
    
    public function actionContacto() {
        $model = new \app\models\FormularioContacto();
        if ($model->load(Yii::$app->request->post()) 
                &&
            $model->contact(Yii::$app->params["contacto"])) {
            Yii::$app->session->setFlash('enviadoContacto');
            
            return $this->refresh();
        }
        
        return $this->render("contacto", [
            "model" => $model,
        ]);
    }
    
    public function actionProductos() {
        $query = Productos::find()->select("id, nombre, foto, descripcion");
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 2,
            ],
        ]);

        return $this->render('productos',[
            'dataProvider' => $dataProvider,
        ]);
    }
    
    public function actionCategorias() {
        $query = Categorias::find()->select("id, nombre, foto, descripcion");
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 2,
            ],
        ]);

        return $this->render('categorias',[
            'dataProvider' => $dataProvider,
        ]);
    }
    
    public function actionDetallecategoria($id) {
        $model = new Categorias();
        $model = Categorias::find()->select('categorias.*')->where(['id' => $id])->one();

        $query = Productos::find()
                 ->joinWith("relacions",false,"INNER JOIN")
                 ->where("categoria=$id");

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);
        
        return $this->render("detalle_categoria",[
            'model' => $model,
            'dataProvider' => $dataProvider,
        ]);

    }
}

views/site/_productos.php
<?php
use app\widgets\Miniaturas;
?>

<div class="col-sm-6 col-md-6">
    <?= Miniaturas::widget([
        'id' => $model->id,
        'nombre' => $model->nombre,
        'descripcion' => $model->descripcion,
        'foto' =>  $model->foto,
    ]) ?>
</div>

views/site/categorias.php
<?php
use yii\grid\GridView;
use yii\helpers\Html;
?>

 <?= GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => [
        'id',
        'nombre',
        'descripcion',
        [
            'attribute' => 'foto',
            'label' => 'foto',
            'content' => function($data) {
                return Html::a(Html::img('@web/imgs/' . $data["foto"], ['width' => '400px']), ['site/detallecategoria','id'=>$data->id]);
            }
        ],
     ]
 ]) ?>

views/site/contacto.php
<?php
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
?>

<?php
if (Yii::$app->session->hasFlash('enviadoContacto')) {
    echo '<div class="alert alert-success">';
    echo 'Solicitud de contacto enviada';
    echo '</div>';
}
?>

<div class="row">
    <div class="col-lg-5">

        <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

            <?= $form->field($model, 'nombre')->textInput(['autofocus' => true]) ?>
        
            <?= $form->field($model, 'apellidos') ?>

            <?= $form->field($model, 'correo') ?>

            <?= $form->field($model, 'asunto')->dropDownList(['General' => 'General', 'Productos' => 'Productos', 'Reclamación' => 'Reclamación']) ?>

            <?= $form->field($model, 'contenido')->textarea(['rows' => 6]) ?>

            <div class="form-group">
                <?= Html::submitButton('Enviar contacto', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
            </div>

        <?php ActiveForm::end(); ?>

    </div>
</div>

views/site/detalle_categoria.php
<?php
use yii\widgets\DetailView;
use yii\grid\GridView;
use yii\helpers\Html;
?>

<?= DetailView::widget([
    'model' => $model,
    'attributes' => [
        'id',
        'nombre',
        'descripcion',
        [
            'label' => 'foto',
            'format' => 'raw',
            'value' => Html::img("@web/imgs/" . $model->foto, [
                'class' => 'fotoDetalleDetailView',
            ]),
            'contentOptions' => ['style' => 'text-align: center;']
        ]
    ]
]) ?>

<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => [
        'id',
        'nombre',
        'descripcion',
        [
            'label' => 'Foto',
            'format' => 'raw',
            'value' => function($data) {
                        return Html::img("@web/imgs/" . $data->foto, [
                            'class' => 'fotoDetalleGridView',
                        ]);
                    },
            'contentOptions' => ['style' => 'text-align: center;']
        ]
    ]
]) ?>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-index">

</div>

views/site/informacion.php
<?php
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
?>

<?php
if (Yii::$app->session->hasFlash('enviadaInformacion')) {
    echo '<div class="alert alert-success">';
    echo 'Solicitud de información enviada';
    echo '</div>';
}
?>

<div class="row">
    <div class="col-lg-5">

        <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

            <?= $form->field($model, 'nombre')->textInput(['autofocus' => true]) ?>

            <?= $form->field($model, 'correo') ?>

            <?= $form->field($model, 'asunto') ?>

            <?= $form->field($model, 'contenido')->textarea(['rows' => 6]) ?>

            <div class="form-group">
                <?= Html::submitButton('Pedir informacion', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
            </div>

        <?php ActiveForm::end(); ?>

    </div>
</div>

views/site/productos.php
<?php
    use yii\widgets\ListView;
?>
<div class="row">
    <?= ListView::widget([
        'dataProvider' => $dataProvider,
        'itemView' => '_productos',
        'layout' => '<div>{summary}</div><br /><div class="container container-fluid">{items}</div><div>{pager}</div>',
    ]); ?>
</div>